### ISSUE TITLE
Check of Nuxt.JS 3 RC can use PWA functionalities

### ISSUE THREAD

**Issue by BT-Creator** [osoc22/project-track-trace#19]
For smartphone data sending, we'll need to have PWA capabilities. Currently, Nuxt.JS 3 RC does **[not have a PWA module and was expected to arrive this summer](https://v3.nuxtjs.org/community/roadmap/#%EF%B8%8F-roadmap)**!

If we can't do this, we'll need to change framework to one that supports PWA capabilities, as it it critical to get location data. Without it, it is plain impossible. There are some reports that it works with the [`pwa-module` package](https://github.com/nuxt-community/pwa-module/issues/492).

**Comment by Scryper** [comment]
Is (this)[https://pwa.nuxtjs.org/setup] what we need ?

**Comment by BT-Creator** [comment]
Seems like it's working! Only thing you'll need to watch out for is the fact that when you are developing, you'll need to **let the service worker bypass the network**. Normal, there shouldn't be any problem with the production version *(We tested it by building a production version and running it locally)*

You can find it here: https://github.com/osoc22/project-track-trace-hackathon. We also got the SCSS Loader working, so that means we'll be able to use SCSS
