### ISSUE TITLE
Add compact hover data to map pin

### ISSUE THREAD

**Issue by BT-Creator** [osoc22/project-track-trace#27]
When hovering over a marker, you should get a compact overview over the tracker info, as detailed in the Figma prototype

**Comment by JoshuaMoelans** [comment]
[This one](https://stackoverflow.com/questions/8523446/openlayers-simple-mouseover-on-marker) is more interesting instead, because it works directly on openlayers. Reading into it, and prepared to implement this next week!

**Comment by JoshuaMoelans** [comment]
For now, we have implemented these via a 'select' event. However, it seems like VueLayers does have some (undocumented) on-hover esque events, which could be useful. An example [can be seen here](https://jsfiddle.net/ghettovoice/g8L96efo/), following [this issue](https://github.com/ghettovoice/vuelayers/issues/110). 

On-click is working more or less 'fine' now, but if we have time and patience left, this hover behaviour could be interesting.
