### ISSUE TITLE
Update Tacker object to representative objects

### ISSUE THREAD

**Issue by BT-Creator** [osoc22/project-track-trace#55]
Yes, we can definitely do this. Not sure if it is needed for this PR, since the format of the trackerDetails might still change when we get the actual data. It's your call, if you want me to make a dummy interface already or not

_Originally posted by @JoshuaMoelans in https://github.com/osoc22/project-track-trace/pull/50#discussion_r921090886_

**Comment by JoshuaMoelans** [comment]
The tracker object is defined as a type called Position, which was merged into main in PR #96 . Think we can close this now?
