### ISSUE TITLE
Remove tracker when stop tracking

### ISSUE THREAD

**Issue by BenJStoffels** [osoc22/project-track-trace#77]
At this point, when you stop tracking, you won't be sending any more locationupdates, but the other clients don't know you stop tracking, so the tracker should dissapear, but there is no way of doing that at this point. This is something that we can look into when we have extra time, but it's definitely not something urgent.

**Comment by JoshuaMoelans** [comment]
Think this was implemented @BenJStoffels ?

**Comment by Scryper** [comment]
Implemented in #85
